image:
  - Visual Studio 2019
clone_folder: c:\projects\cm

install:
  - set QTDIR=C:\Qt\5.14.2\mingw73_64
  - set PATH=%QTDIR%\bin;C:\Qt\tools\mingw730_64\bin;%PATH%

build_script:
- cmd: >-

    cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=%QTDIR%\lib\cmake\Qt5 -G "MinGW Makefiles" .

    cmake --build . --target all

test_script:
  ctest -C Release -VV --output-on-failure --output-junit parserTest_res.xml
  $wc = New-Object 'System.Net.WebClient'
  $wc.UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\parserTest_res.xml))
