image:
  - Visual Studio 2019
clone_folder: c:\projects\cm_src

before_build:
  - set QTDIR=C:\Qt\5.14.2\mingw73_64
  - set PATH=%QTDIR%\bin;C:\MinGW\bin;%PATH%

build_script:
- cmd: >-
 
    mkdir build
    
    cmake -G "MinGW Makefiles" .
    
    cd build
    
    cmake --build . 

test_script:
- cmd: ctest -C Debug
