image:
  - Visual Studio 2019
clone_folder: c:\projects\cm

install:
  - set QTDIR=C:\Qt\5.14.2\mingw73_64
  - set PATH=%PATH%;%QTDIR%\bin;C:\MinGW\bin

build_script:
- cmd: >-

    mkdir build

    cd build

    cmake --build --target all --config "Release"

test_script:
- cmd: ctest -C Debug
